#sonar.projectKey=marco-milanese-sonarsource_kilo
sonar.projectKey=marco-milanese-sonarsource_kilo_2622f0c1-4be5-4982-b0a1-29e78def63dc
sonar.organization=marco-milanese-sonarsource


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=kilo
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
