name: SonarQube
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install llvm tools
        run: sudo apt-get install -y llvm
      - name: Generate compilation database
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Run tests to generate coverage information
        run: |
          ./build/test_kilo
          mv default.profraw test_kilo.profraw
      - name: Merge counters from different runs and convert the result into an llvm-cov-compatible form
        run: |
          llvm-profdata merge -o merged.profdata -- ./*.profraw
      - name: Collect the coverage
        run: |
          llvm-cov show --show-branches=count --instr-profile merged.profdata build/test_kilo > coverage.txt
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: > 
            --define sonar.cfamily.compile-commands=build/compile_commands.json
            --define sonar.cfamily.llvm-cov.reportPath=coverage.txt
